import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { ToggleNavProvider } from "@/context/ToggleNavContext";
import AuthProvider from "@/context/AuthProvider";
import { NavbarCategoryProvider } from "@/context/CategoryContext";
import { Toaster } from "react-hot-toast";
import { SortByProvider } from "@/context/sortByContext";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${jost.className}`}>
        <NavbarCategoryProvider>
          <SortByProvider>
            <ToggleNavProvider>
              <AuthProvider>
                <Toaster
                  position="top-center"
                  gutter={12}
                  containerStyle={{ margin: "8px" }}
                  toastOptions={{
                    success: {
                      duration: 3000,
                    },
                    error: {
                      duration: 5000,
                    },
                    style: {
                      fontSize: "16px",
                      maxWidth: "500px",
                      padding: "16px 24px",
                      backgroundColor: "rgb(100, 113, 150)",
                      color: "rgb(247, 248, 253)",
                    },
                  }}
                />
                {children}
              </AuthProvider>
            </ToggleNavProvider>
          </SortByProvider>
        </NavbarCategoryProvider>
      </body>
    </html>
  );
}
